### ISSUE TITLE
Error on some videos

### ISSUE THREAD

**Issue by zelenooki87** [Annbless/DUTCode#4]
`(DUTCode) C:\Users\Milan\DUTCode>sh ./scripts/deploy_samples.sh
Directory exists
 Stabiling using the DUT model
-----------------------------------
Namespace(InputBasePath='images/', MaxLength=1200, MotionProPath='ckpt/MotionPro.pth', OutNamePrefix='', OutputBasePath='results/', PWCNetPath='ckpt/network-default.pytorch', RFDetPath='ckpt/RFDet_640.pth.tar', Repeat=50, SingleHomo=False, SmootherPath='ckpt/smoother.pth')
-------------model configuration------------------------
using RFNet ...
using PWCNet for motion estimation...
using Motion Propagation model with multi homo...
using Deep Smoother Model...
------------------reload parameters-------------------------
reload Smoother params
successfully load 12 params for smoother
reload RFDet Model
successfully load 100 params for RFDet
reload PWCNet Model
reload MotionPropagation Model
successfully load 21 params for MotionPropagation
Traceback (most recent call last):
  File "./scripts/DUTStabilizer.py", line 111, in <module>
    generateStable(model, inPath, outPath, outPrefix, maxlength, args)
  File "./scripts/DUTStabilizer.py", line 42, in generateStable
    image = image * (1. / 255.)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
 Stabiling using the DIFRINT model
-----------------------------------
C:\Users\Milan\miniconda3\envs\DUTCode\python.exe: can't open file './scripts/DIFRINTStabilizer.py': [Errno 2] No such file or directory
 Stabiling using the DIFRINT model
-----------------------------------
Traceback (most recent call last):
  File "./scripts/StabNetStabilizer.py", line 83, in <module>
    image = cv2.resize(image, (width, height))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'`
on windows 10, miniconda envionment
please tell me where I am wrong?

**Comment by Annbless** [comment]
Emmmm. this is a strange error. I checked the code on line 42 in the "generateStable" function, which reads the image. Could you please print out the path to the image and check if there is a problem with the path or the image file?
